3 pasrt of tasks
js-tasks-ru/js-20220513_pavel-glukhov pull request #4
Opened 2022-05-24 15:11 UTC by bill-gilbert

added solution for 4 tasks

2022-05-24 15:13 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-24 15:37 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-05-24 16:04 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    let arr = path.split(`.`);
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2022-05-24 16:04 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
>  export function invertObj(obj) {
good 👍

2022-05-24 16:04 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
>  export function trimSymbols(string, size) {
good 👍

2022-05-24 16:04 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  for (let i = 1; i < arr.length; i++) {
попробуйте решить задачу альтернативным способов - используя коллекцию `Set`

2022-05-24 16:05 UTC, dosandk requested changes
решение createGetter следует поправить

2022-05-24 17:13 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-05-24 20:04 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-27 08:31 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  let arr = path.split(`.`);
good 👍

2022-05-27 08:32 UTC, dosandk approved these changes
good 👍

2022-05-27 08:32 UTC, merged